# SPDX-FileCopyrightText: 2016-2026 PyThaiNLP Project
# SPDX-FileCopyrightText: 2026 Thapthim Project Contributor suphasan-kh
# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0

# Character type table from TIS 1566-2541

module Thapthim
  CHAR_TYPE = Hash.new(:NON).merge!({
    "ก" => :CONS, 
    "ข" => :CONS, 
    "ฃ" => :CONS, 
    "ค" => :CONS, 
    "ฅ" => :CONS, 
    "ฆ" => :CONS, 
    "ง" => :CONS, 
    "จ" => :CONS, 
    "ฉ" => :CONS, 
    "ช" => :CONS, 
    "ซ" => :CONS, 
    "ฌ" => :CONS, 
    "ญ" => :CONS, 
    "ฎ" => :CONS, 
    "ฏ" => :CONS, 
    "ฐ" => :CONS, 
    "ฑ" => :CONS, 
    "ฒ" => :CONS, 
    "ณ" => :CONS, 
    "ด" => :CONS, 
    "ต" => :CONS, 
    "ถ" => :CONS, 
    "ท" => :CONS, 
    "ธ" => :CONS, 
    "น" => :CONS, 
    "บ" => :CONS, 
    "ป" => :CONS, 
    "ผ" => :CONS, 
    "ฝ" => :CONS, 
    "พ" => :CONS, 
    "ฟ" => :CONS, 
    "ภ" => :CONS, 
    "ม" => :CONS, 
    "ย" => :CONS, 
    "ร" => :CONS, 
    "ฤ" => :FV3, 
    "ล" => :CONS, 
    "ฦ" => :FV3, 
    "ว" => :CONS, 
    "ศ" => :CONS, 
    "ษ" => :CONS, 
    "ส" => :CONS, 
    "ห" => :CONS, 
    "ฬ" => :CONS, 
    "อ" => :CONS, 
    "ฮ" => :CONS, 
    "ฯ" => :NON, 
    "ะ" => :FV1, 
    "ั" => :AV2, 
    "า" => :FV1, 
    "ำ" => :FV1, 
    "ิ" => :AV1, 
    "ี" => :AV3, 
    "ึ" => :AV2, 
    "ื" => :AV3, 
    "ุ" => :BV1, 
    "ู" => :BV2, 
    "ฺ" => :BD, 
    "฿" => :NON, 
    "เ" => :LV, 
    "แ" => :LV, 
    "โ" => :LV, 
    "ใ" => :LV, 
    "ไ" => :LV, 
    "ๅ" => :FV2, 
    "ๆ" => :NON, 
    "็" => :AD2, 
    "่" => :TONE, 
    "้" => :TONE, 
    "๊" => :TONE, 
    "๋" => :TONE, 
    "์" => :AD1, 
    "ํ" => :AD1, 
    "๎" => :AD3, 
    "๏" => :NON, 
    "๐" => :NON, 
    "๑" => :NON, 
    "๒" => :NON, 
    "๓" => :NON, 
    "๔" => :NON, 
    "๕" => :NON, 
    "๖" => :NON, 
    "๗" => :NON, 
    "๘" => :NON, 
    "๙" => :NON, 
    "๚" => :NON, 
    "๛" => :NON, 
  }).freeze

  # A is accept, R is reject, S is strict reject
  RULES = Hash.new {|hash, key| hash[key] = Hash.new(:A)}

  # NON row
  RULES[:NON][:FV1] = :S
  RULES[:NON][:FV2] = :S
  RULES[:NON][:BV1] = :R
  RULES[:NON][:BV2] = :R
  RULES[:NON][:BD] = :R
  RULES[:NON][:TONE] = :R
  RULES[:NON][:AD1] = :R
  RULES[:NON][:AD2] = :R
  RULES[:NON][:AD3] = :R
  RULES[:NON][:AV1] = :R
  RULES[:NON][:AV2] = :R
  RULES[:NON][:AV3] = :R

  # CONS row
  RULES[:CONS][:FV2] = :S

  # LV row
  RULES[:LV][:NON] = :S
  RULES[:LV][:LV] = :S
  RULES[:LV][:FV1] = :S
  RULES[:LV][:FV2] = :S
  RULES[:LV][:FV3] = :S
  RULES[:LV][:BV1] = :R
  RULES[:LV][:BV2] = :R
  RULES[:LV][:BD] = :R
  RULES[:LV][:TONE] = :R
  RULES[:LV][:AD1] = :R
  RULES[:LV][:AD2] = :R
  RULES[:LV][:AD3] = :R
  RULES[:LV][:AV1] = :R
  RULES[:LV][:AV2] = :R
  RULES[:LV][:AV3] = :R

  # FV1 row
  RULES[:FV1][:NON] = :S
  RULES[:FV1][:FV1] = :S
  RULES[:FV1][:FV2] = :S
  RULES[:FV1][:FV3] = :S
  RULES[:FV1][:BV1] = :R
  RULES[:FV1][:BV2] = :R
  RULES[:FV1][:BD] = :R
  RULES[:FV1][:TONE] = :R
  RULES[:FV1][:AD1] = :R
  RULES[:FV1][:AD2] = :R
  RULES[:FV1][:AD3] = :R
  RULES[:FV1][:AV1] = :R
  RULES[:FV1][:AV2] = :R
  RULES[:FV1][:AV3] = :R

  # FV2 row
  RULES[:FV2][:FV2] = :S
  RULES[:FV2][:BV1] = :R
  RULES[:FV2][:BV2] = :R
  RULES[:FV2][:BD] = :R
  RULES[:FV2][:TONE] = :R
  RULES[:FV2][:AD1] = :R
  RULES[:FV2][:AD2] = :R
  RULES[:FV2][:AD3] = :R
  RULES[:FV2][:AV1] = :R
  RULES[:FV2][:AV2] = :R
  RULES[:FV2][:AV3] = :R

  # FV3 row
  RULES[:FV3][:FV1] = :S
  RULES[:FV3][:FV3] = :S
  RULES[:FV3][:BV1] = :R
  RULES[:FV3][:BV2] = :R
  RULES[:FV3][:BD] = :R
  RULES[:FV3][:TONE] = :R
  RULES[:FV3][:AD1] = :R
  RULES[:FV3][:AD2] = :R
  RULES[:FV3][:AD3] = :R
  RULES[:FV3][:AV1] = :R
  RULES[:FV3][:AV2] = :R
  RULES[:FV3][:AV3] = :R

  # Skip CTRL

  # BV1 row
  RULES[:BV1][:FV1] = :S
  RULES[:BV1][:FV2] = :S
  RULES[:BV1][:BV1] = :R
  RULES[:BV1][:BV2] = :R
  RULES[:BV1][:BD] = :R
  RULES[:BV1][:AD2] = :R
  RULES[:BV1][:AD3] = :R
  RULES[:BV1][:AV1] = :R
  RULES[:BV1][:AV2] = :R
  RULES[:BV1][:AV3] = :R

  # BV2 row
  RULES[:BV2][:FV1] = :S
  RULES[:BV2][:FV2] = :S
  RULES[:BV2][:BV1] = :R
  RULES[:BV2][:BV2] = :R
  RULES[:BV2][:BD] = :R
  RULES[:BV2][:AD1] = :R
  RULES[:BV2][:AD2] = :R
  RULES[:BV2][:AD3] = :R
  RULES[:BV2][:AV1] = :R
  RULES[:BV2][:AV2] = :R
  RULES[:BV2][:AV3] = :R

  # BD row
  RULES[:BD][:FV1] = :S
  RULES[:BD][:FV2] = :S
  RULES[:BD][:BV1] = :R
  RULES[:BD][:BV2] = :R
  RULES[:BD][:BD] = :R
  RULES[:BD][:TONE] = :R
  RULES[:BD][:AD1] = :R
  RULES[:BD][:AD2] = :R
  RULES[:BD][:AD3] = :R
  RULES[:BD][:AV1] = :R
  RULES[:BD][:AV2] = :R
  RULES[:BD][:AV3] = :R

  # TONE row
  RULES[:TONE][:BV1] = :R
  RULES[:TONE][:BV2] = :R
  RULES[:TONE][:BD] = :R
  RULES[:TONE][:TONE] = :R
  RULES[:TONE][:AD1] = :R
  RULES[:TONE][:AD2] = :R
  RULES[:TONE][:AD3] = :R
  RULES[:TONE][:AV1] = :R
  RULES[:TONE][:AV2] = :R
  RULES[:TONE][:AV3] = :R

  # AD1 row
  RULES[:AD1][:FV1] = :S
  RULES[:AD1][:FV2] = :S
  RULES[:AD1][:BV1] = :R
  RULES[:AD1][:BV2] = :R
  RULES[:AD1][:BD] = :R
  RULES[:AD1][:TONE] = :R
  RULES[:AD1][:AD1] = :R
  RULES[:AD1][:AD2] = :R
  RULES[:AD1][:AD3] = :R
  RULES[:AD1][:AV1] = :R
  RULES[:AD1][:AV2] = :R
  RULES[:AD1][:AV3] = :R

  # AD2 row
  RULES[:AD2][:FV1] = :S
  RULES[:AD2][:FV2] = :S
  RULES[:AD2][:BV1] = :R
  RULES[:AD2][:BV2] = :R
  RULES[:AD2][:BD] = :R
  RULES[:AD2][:TONE] = :R
  RULES[:AD2][:AD1] = :R
  RULES[:AD2][:AD2] = :R
  RULES[:AD2][:AD3] = :R
  RULES[:AD2][:AV1] = :R
  RULES[:AD2][:AV2] = :R
  RULES[:AD2][:AV3] = :R

  # AD3 row
  RULES[:AD3][:FV1] = :S
  RULES[:AD3][:FV2] = :S
  RULES[:AD3][:BV1] = :R
  RULES[:AD3][:BV2] = :R
  RULES[:AD3][:BD] = :R
  RULES[:AD3][:TONE] = :R
  RULES[:AD3][:AD1] = :R
  RULES[:AD3][:AD2] = :R
  RULES[:AD3][:AD3] = :R
  RULES[:AD3][:AV1] = :R
  RULES[:AD3][:AV2] = :R
  RULES[:AD3][:AV3] = :R

  # AV1 row
  RULES[:AV1][:FV1] = :S
  RULES[:AV1][:FV2] = :S
  RULES[:AV1][:BV1] = :R
  RULES[:AV1][:BV2] = :R
  RULES[:AV1][:BD] = :R
  RULES[:AV1][:AD2] = :R
  RULES[:AV1][:AD3] = :R
  RULES[:AV1][:AV1] = :R
  RULES[:AV1][:AV2] = :R
  RULES[:AV1][:AV3] = :R

  # AV2 row
  RULES[:AV2][:FV1] = :S
  RULES[:AV2][:FV2] = :S
  RULES[:AV2][:BV1] = :R
  RULES[:AV2][:BV2] = :R
  RULES[:AV2][:BD] = :R
  RULES[:AV2][:AD1] = :R
  RULES[:AV2][:AD2] = :R
  RULES[:AV2][:AD3] = :R
  RULES[:AV2][:AV1] = :R
  RULES[:AV2][:AV2] = :R
  RULES[:AV2][:AV3] = :R

  # AV3 row
  RULES[:AV3][:FV1] = :S
  RULES[:AV3][:FV2] = :S
  RULES[:AV3][:BV1] = :R
  RULES[:AV3][:BV2] = :R
  RULES[:AV3][:BD] = :R
  RULES[:AV3][:AD1] = :R
  RULES[:AV3][:AD3] = :R
  RULES[:AV3][:AV1] = :R
  RULES[:AV3][:AV2] = :R
  RULES[:AV3][:AV3] = :R

  private_constant :CHAR_TYPE, :RULES
end