module Thapthim
  CHAR_TYPE = Hash.new("NON").merge!({
    "ก" => "CONS", 
    "ข" => "CONS", 
    "ฃ" => "CONS", 
    "ค" => "CONS", 
    "ฅ" => "CONS", 
    "ฆ" => "CONS", 
    "ง" => "CONS", 
    "จ" => "CONS", 
    "ฉ" => "CONS", 
    "ช" => "CONS", 
    "ซ" => "CONS", 
    "ฌ" => "CONS", 
    "ญ" => "CONS", 
    "ฎ" => "CONS", 
    "ฏ" => "CONS", 
    "ฐ" => "CONS", 
    "ฑ" => "CONS", 
    "ฒ" => "CONS", 
    "ณ" => "CONS", 
    "ด" => "CONS", 
    "ต" => "CONS", 
    "ถ" => "CONS", 
    "ท" => "CONS", 
    "ธ" => "CONS", 
    "น" => "CONS", 
    "บ" => "CONS", 
    "ป" => "CONS", 
    "ผ" => "CONS", 
    "ฝ" => "CONS", 
    "พ" => "CONS", 
    "ฟ" => "CONS", 
    "ภ" => "CONS", 
    "ม" => "CONS", 
    "ย" => "CONS", 
    "ร" => "CONS", 
    "ฤ" => "FV3", 
    "ล" => "CONS", 
    "ฦ" => "FV3", 
    "ว" => "CONS", 
    "ศ" => "CONS", 
    "ษ" => "CONS", 
    "ส" => "CONS", 
    "ห" => "CONS", 
    "ฬ" => "CONS", 
    "อ" => "CONS", 
    "ฮ" => "CONS", 
    "ฯ" => "NON", 
    "ะ" => "FV1", 
    "ั" => "AV2", 
    "า" => "FV1", 
    "ำ" => "FV1", 
    "ิ" => "AV1", 
    "ี" => "AV3", 
    "ึ" => "AV2", 
    "ื" => "AV3", 
    "ุ" => "BV1", 
    "ู" => "BV2", 
    "ฺ" => "BD", 
    "฿" => "NON", 
    "เ" => "LV", 
    "แ" => "LV", 
    "โ" => "LV", 
    "ใ" => "LV", 
    "ไ" => "LV", 
    "ๅ" => "FV2", 
    "ๆ" => "NON", 
    "็" => "AD2", 
    "่" => "TONE", 
    "้" => "TONE", 
    "๊" => "TONE", 
    "๋" => "TONE", 
    "์" => "AD1", 
    "ํ" => "AD1", 
    "๎" => "AD3", 
    "๏" => "NON", 
    "๐" => "NON", 
    "๑" => "NON", 
    "๒" => "NON", 
    "๓" => "NON", 
    "๔" => "NON", 
    "๕" => "NON", 
    "๖" => "NON", 
    "๗" => "NON", 
    "๘" => "NON", 
    "๙" => "NON", 
    "๚" => "NON", 
    "๛" => "NON", 
  })

  # 0 is accept, 1 is reject, 2 is strict reject
  RULES = Hash.new {|hash, key| hash[key] = Hash.new(0)}

  # NON row
  RULES["NON"]["FV1"] = 2
  RULES["NON"]["FV2"] = 2
  RULES["NON"]["BV1"] = 1
  RULES["NON"]["BV2"] = 1
  RULES["NON"]["BD"] = 1
  RULES["NON"]["TONE"] = 1
  RULES["NON"]["AD1"] = 1
  RULES["NON"]["AD2"] = 1
  RULES["NON"]["AD3"] = 1
  RULES["NON"]["AV1"] = 1
  RULES["NON"]["AV2"] = 1
  RULES["NON"]["AV3"] = 1

  # CONS row
  RULES["CONS"]["FV2"] = 2

  # LV row
  RULES["LV"]["NON"] = 2
  RULES["LV"]["LV"] = 2
  RULES["LV"]["FV1"] = 2
  RULES["LV"]["FV2"] = 2
  RULES["LV"]["FV3"] = 2
  RULES["LV"]["BV1"] = 1
  RULES["LV"]["BV2"] = 1
  RULES["LV"]["BD"] = 1
  RULES["LV"]["TONE"] = 1
  RULES["LV"]["AD1"] = 1
  RULES["LV"]["AD2"] = 1
  RULES["LV"]["AD3"] = 1
  RULES["LV"]["AV1"] = 1
  RULES["LV"]["AV2"] = 1
  RULES["LV"]["AV3"] = 1

  # FV1 row
  RULES["FV1"]["NON"] = 2
  RULES["FV1"]["FV1"] = 2
  RULES["FV1"]["FV2"] = 2
  RULES["FV1"]["FV3"] = 2
  RULES["FV1"]["BV1"] = 1
  RULES["FV1"]["BV2"] = 1
  RULES["FV1"]["BD"] = 1
  RULES["FV1"]["TONE"] = 1
  RULES["FV1"]["AD1"] = 1
  RULES["FV1"]["AD2"] = 1
  RULES["FV1"]["AD3"] = 1
  RULES["FV1"]["AV1"] = 1
  RULES["FV1"]["AV2"] = 1
  RULES["FV1"]["AV3"] = 1

  # FV2 row
  RULES["FV2"]["FV2"] = 2
  RULES["FV2"]["BV1"] = 1
  RULES["FV2"]["BV2"] = 1
  RULES["FV2"]["BD"] = 1
  RULES["FV2"]["TONE"] = 1
  RULES["FV2"]["AD1"] = 1
  RULES["FV2"]["AD2"] = 1
  RULES["FV2"]["AD3"] = 1
  RULES["FV2"]["AV1"] = 1
  RULES["FV2"]["AV2"] = 1
  RULES["FV2"]["AV3"] = 1

  # FV3 row
  RULES["FV3"]["FV1"] = 2
  RULES["FV3"]["FV3"] = 2
  RULES["FV3"]["BV1"] = 1
  RULES["FV3"]["BV2"] = 1
  RULES["FV3"]["BD"] = 1
  RULES["FV3"]["TONE"] = 1
  RULES["FV3"]["AD1"] = 1
  RULES["FV3"]["AD2"] = 1
  RULES["FV3"]["AD3"] = 1
  RULES["FV3"]["AV1"] = 1
  RULES["FV3"]["AV2"] = 1
  RULES["FV3"]["AV3"] = 1

  # Skip CTRL

  # BV1 row
  RULES["BV1"]["FV1"] = 2
  RULES["BV1"]["FV2"] = 2
  RULES["BV1"]["BV1"] = 1
  RULES["BV1"]["BV2"] = 1
  RULES["BV1"]["BD"] = 1
  RULES["BV1"]["AD2"] = 1
  RULES["BV1"]["AD3"] = 1
  RULES["BV1"]["AV1"] = 1
  RULES["BV1"]["AV2"] = 1
  RULES["BV1"]["AV3"] = 1

  # BV2 row
  RULES["BV2"]["FV1"] = 2
  RULES["BV2"]["FV2"] = 2
  RULES["BV2"]["BV1"] = 1
  RULES["BV2"]["BV2"] = 1
  RULES["BV2"]["BD"] = 1
  RULES["BV2"]["AD1"] = 1
  RULES["BV2"]["AD2"] = 1
  RULES["BV2"]["AD3"] = 1
  RULES["BV2"]["AV1"] = 1
  RULES["BV2"]["AV2"] = 1
  RULES["BV2"]["AV3"] = 1

  # BD row
  RULES["BD"]["FV1"] = 2
  RULES["BD"]["FV2"] = 2
  RULES["BD"]["BV1"] = 1
  RULES["BD"]["BV2"] = 1
  RULES["BD"]["BD"] = 1
  RULES["BD"]["TONE"] = 1
  RULES["BD"]["AD1"] = 1
  RULES["BD"]["AD2"] = 1
  RULES["BD"]["AD3"] = 1
  RULES["BD"]["AV1"] = 1
  RULES["BD"]["AV2"] = 1
  RULES["BD"]["AV3"] = 1

  # TONE row
  RULES["TONE"]["BV1"] = 1
  RULES["TONE"]["BV2"] = 1
  RULES["TONE"]["BD"] = 1
  RULES["TONE"]["TONE"] = 1
  RULES["TONE"]["AD1"] = 1
  RULES["TONE"]["AD2"] = 1
  RULES["TONE"]["AD3"] = 1
  RULES["TONE"]["AV1"] = 1
  RULES["TONE"]["AV2"] = 1
  RULES["TONE"]["AV3"] = 1

  # AD1 row
  RULES["AD1"]["FV1"] = 2
  RULES["AD1"]["FV2"] = 2
  RULES["AD1"]["BV1"] = 1
  RULES["AD1"]["BV2"] = 1
  RULES["AD1"]["BD"] = 1
  RULES["AD1"]["TONE"] = 1
  RULES["AD1"]["AD1"] = 1
  RULES["AD1"]["AD2"] = 1
  RULES["AD1"]["AD3"] = 1
  RULES["AD1"]["AV1"] = 1
  RULES["AD1"]["AV2"] = 1
  RULES["AD1"]["AV3"] = 1

  # AD2 row
  RULES["AD2"]["FV1"] = 2
  RULES["AD2"]["FV2"] = 2
  RULES["AD2"]["BV1"] = 1
  RULES["AD2"]["BV2"] = 1
  RULES["AD2"]["BD"] = 1
  RULES["AD2"]["TONE"] = 1
  RULES["AD2"]["AD1"] = 1
  RULES["AD2"]["AD2"] = 1
  RULES["AD2"]["AD3"] = 1
  RULES["AD2"]["AV1"] = 1
  RULES["AD2"]["AV2"] = 1
  RULES["AD2"]["AV3"] = 1

  # AD3 row
  RULES["AD3"]["FV1"] = 2
  RULES["AD3"]["FV2"] = 2
  RULES["AD3"]["BV1"] = 1
  RULES["AD3"]["BV2"] = 1
  RULES["AD3"]["BD"] = 1
  RULES["AD3"]["TONE"] = 1
  RULES["AD3"]["AD1"] = 1
  RULES["AD3"]["AD2"] = 1
  RULES["AD3"]["AD3"] = 1
  RULES["AD3"]["AV1"] = 1
  RULES["AD3"]["AV2"] = 1
  RULES["AD3"]["AV3"] = 1

  # AV1 row
  RULES["AV1"]["FV1"] = 2
  RULES["AV1"]["FV2"] = 2
  RULES["AV1"]["BV1"] = 1
  RULES["AV1"]["BV2"] = 1
  RULES["AV1"]["BD"] = 1
  RULES["AV1"]["AD2"] = 1
  RULES["AV1"]["AD3"] = 1
  RULES["AV1"]["AV1"] = 1
  RULES["AV1"]["AV2"] = 1
  RULES["AV1"]["AV3"] = 1

  # AV2 row
  RULES["AV2"]["FV1"] = 2
  RULES["AV2"]["FV2"] = 2
  RULES["AV2"]["BV1"] = 1
  RULES["AV2"]["BV2"] = 1
  RULES["AV2"]["BD"] = 1
  RULES["AV2"]["AD1"] = 1
  RULES["AV2"]["AD2"] = 1
  RULES["AV2"]["AD3"] = 1
  RULES["AV2"]["AV1"] = 1
  RULES["AV2"]["AV2"] = 1
  RULES["AV2"]["AV3"] = 1

  # AV3 row
  RULES["AV3"]["FV1"] = 2
  RULES["AV3"]["FV2"] = 2
  RULES["AV3"]["BV1"] = 1
  RULES["AV3"]["BV2"] = 1
  RULES["AV3"]["BD"] = 1
  RULES["AV3"]["AD1"] = 1
  RULES["AV3"]["AD3"] = 1
  RULES["AV3"]["AV1"] = 1
  RULES["AV3"]["AV2"] = 1
  RULES["AV3"]["AV3"] = 1

  private_constant :CHAR_TYPE, :RULES
end